all:
  hosts:
    node1:
      ansible_host: 192.168.0.201
      ip: 192.168.0.201
      access_ip: 192.168.0.201
      ansible_user: vagrant
    node2:
      ansible_host: 192.168.0.202
      ip: 192.168.0.202
      access_ip: 192.168.0.202
      ansible_user: vagrant
    node3:
      ansible_host: 192.168.0.203
      ip: 192.168.0.203
      access_ip: 192.168.0.203
      ansible_user: vagrant
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube_control_plane:
        kube-node:
    calico-rr:
      hosts: {}
